### ISSUE TITLE
Monitoring Template at Wrong Level

### ISSUE THREAD

**Issue by sempervictus** [daviswr/ZenPacks.daviswr.SMART#3]
The SMART monitoring template can be applied to `/`, but is not available in `/Sever/SSH/Linux` unless copied manually by the user.

**Comment by sempervictus** [comment]
Actually, even when manually copied by the user, the template cannot be applied at `/Server/SSH/Linux` or devices therein.
EDIT: ... nor is can it be bound to `/`

**Comment by daviswr** [comment]
It's a component-level template, for storage devices modeled by the `daviswr.cmd.SMART` modeler, rather than a device-level template. Add that modeler to your `/Server/SSH/Linux` device class. It'll be in the readme, which I'm working on... promise :)

**Comment by sempervictus** [comment]
So i have:
![image](https://user-images.githubusercontent.com/1331084/141472792-6e60de2d-d0a2-4afd-8e24-c67a02087153.png)
Which i cannot assign to the server
![image](https://user-images.githubusercontent.com/1331084/141472939-b9789856-8eb0-47aa-a04d-717a139858b5.png)
although i do have the _modeler_ assigned and have set the hard disks param to nothing (hoping to get them all).
When i model, i can see 
```
2021-11-12 13:30:23,482 INFO zen.ZenModeler: Modeler daviswr.cmd.ZFS processing data for device 192.168.63.210
2021-11-12 13:30:23,540 INFO zen.ZenModeler: zZFSDatasetIgnoreTypes set to ['snapshot']
2021-11-12 13:30:23,842 INFO zen.ZenModeler: Modeler daviswr.cmd.SMART processing data for device 192.168.63.210
2021-11-12 13:30:24,122 INFO zen.ZenModeler: Modeler zenoss.cmd.linux.interfaces processing data for device 192.168.63.210
```
but no graph points appear on the hard drive components...
PEBKAC i imagine, or a Zenoss 6 related weirdness? Standing up another 6 tonight to test on a clean instance.

**Comment by sempervictus** [comment]
Yay, SMART components appeared.
That said, they _all_ read as having `100` reallocated sectors (scary):
![image](https://user-images.githubusercontent.com/1331084/141476181-6395d456-ff42-4667-9240-96f7a8ad4daa.png)
that drive in the CLI reads as:
```
# smartctl -iAH /dev/sdaa|grep Real
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
```
Also not sure where its getting the read errors of `83`:
```
 smartctl -iAH /dev/sdaa|grep Err
  1 Raw_Read_Error_Rate     0x000f   083   064   044    Pre-fail  Always       -       182532472
  7 Seek_Error_Rate         0x000f   078   060   045    Pre-fail  Always       -       67953989
184 End-to-End_Error        0x0032   100   100   099    Old_age   Always       -       0
191 G-Sense_Error_Rate      0x0032   097   097   000    Old_age   Always       -       6287
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0023   100   100   001    Pre-fail  Always       -       0
```

**Comment by daviswr** [comment]
As far I can tell, the normalized "Value" column (as opposed to "Raw") in smartctl is the "health" value and lower is worse, and if it gets lower than the associated threshold, that's cause for alarm. Not all vendors scale this 0-100, WD seems to do 0-200 for some things and I try to detect and adjust for it.

So I would read that as the _health rating_ for the number of realllocated sectors is 100%, and is probably fine. The "Health" graph should have units set to percentage, does that not show up on 6? I might have to adjust the legend format to include %, then.

As for read errors, your `Raw_Read_Error_Rate` normalized value in that smartctl output is 083. I decided not to treat the "Raw" value as an additional counter due to what I read on https://wiki.unraid.net/Understanding_SMART_Reports#1_Raw_Read_Error_Rate , which reports:
> Only Seagates report the raw value, which yes, does appear to be the number of raw read errors, but should be ignored, completely. All other drives have raw read errors too, but do not report them, leaving this value as zero only.

Rated Lifetime is the normalized value for `Power_On_Hours`, or `Power_Cycle_Count` if `Power_On_Hours` isn't available.

Now, what it graphs as "overall" health is whatever the lowest normalized value that's not otherwise graphed, temperature, or reporting 0 with a threshold of 0, so whatever is causing a value of 5 for that is likely worth looking into. Could be nothing and I might need to adjust the parser (I suspect there's going to be a lot of that), but who knows. Turns out SMART is a bit of a mess and includes a fair amount of guesswork.

Writing this, I'm realizing the readme needs a section talking about this topic, so I'll get that added, too.

**Comment by sempervictus** [comment]
Thanks for the clarification.
For reallocated sectors, a % might not be a good way to go. Say you have 1000000 sectors, and 1 goes bad - at some of our clients, the _first_ reallocated sector is cause for replacement. Since 1/1000000 is < 0.5%, wouldn't it round down to 0% impacted? I think that counter might make more sense as raw data since we're looking for # of sectors affected rather than the percentage unaffected (as thats always expected to be 100, or you're in "problem territory").

**Comment by daviswr** [comment]
As for reallocated sectors, there's a [dedicated graph](https://github.com/daviswr/ZenPacks.daviswr.SMART/blob/2dfd52fd3c1e82cbbdb8219a6aa8144c5d567290/ZenPacks/daviswr/SMART/zenpack.yaml#L247) for that which does treat the raw value for `Reallocated_Sector_Ct` as a counter, along with `Current_Pending_Sector` as a gauge value. It's the forth one in the template, under Health, Temperature, and PHY Events. I wouldn't mind bumping it to second, under the Health %, to be more visible.

The health % values are straight out of the smartctl output, not something being calculated by the pack.
EDIT: The parser does scale them to 1-100 for values greater than 100. I have some WD drives whose nominal values are 200, and some VMware documentation I've found indicated that values up to 253 are possible.

**Comment by daviswr** [comment]
Adding some enhancements for alerting when reallocation has occurred. [This paper](https://research.google/pubs/pub32774/) agrees that any reallocated sectors are pretty damning evidence for failure.

**Comment by sempervictus** [comment]
Thank you sir. On the move all day, but will pull & build/deploy this evening
